api:
    build: .
    hostname: api
    log_driver: "syslog"
    command: ./startup.sh
    volumes:
        - .:/app
        - ./config:/config
    dns:
        - 172.16.24.105
        - 10.6.10.208
        - 8.8.8.8
        - 8.8.4.4
    env_file:
        - .env
    ports:
        - "8000:8000"

nginx:
    image: nginx:1.7
    #log_driver: "syslog"
    links:
        - api:backend
    volumes:
        - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        - .:/app
    ports:
        - "80:80"
        - "443:443"
